spring:
  application:
    name: exchange-rate-api

#https://springdoc.org/v2/#properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    display-request-duration: true
    path: /swagger-ui
    filter: true
  show-actuator: true

ecb:
  url: https://www.ecb.europa.eu/